
services:
  db:
    image: postgres:16
    container_name: mockdbv2
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: tariffs
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d tariffs"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata2:
